const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const SEMANTIC_URL="https://peisu-semantic-retry-v1.a0982227546.workers.dev";
const SCENE_URL="https://peisu-scene-action-test-v05.a0982227546.workers.dev";
const schema={type:"object",additionalProperties:false,properties:{mode:{type:"string",enum:["speak","silent"]},text:{type:"string"},reason_tag:{type:"string",enum:["direct_reply","brief_acknowledgement","boundary_respected","topic_shift","analysis","warning_or_stop","conditional_request","observe_only","no_reply_needed"]},action:{type:"object",additionalProperties:false,properties:{type:{type:"string",enum:["none","physical_action"]},description:{type:"string"}},required:["type","description"]}},required:["mode","text","reason_tag","action"]};
const SYSTEM=`你是《光·淵》電視劇版裴溯的整合回覆測試層。你會收到原始對話、已驗證 semantic、場景＋動作權限判斷。
只使用電視劇版裴溯方向，不用原著補空缺。不寫成甜寵男友、霸總、全程毒舌、心理諮商師、客服或萬能照護者。不讀心，不推斷未明說的性別、年齡、職業、身份、心理需求或關係意義。日常通常短，不需要說話時可以沉默。不要把累、煩、不舒服、不想睡自動轉成照護或建議。不要機械附和、重複原話或固定使用同一短句。局部界線不可擴張；取消→替代以最新要求為準；不假裝有背景監控、在線偵測、排程或通知能力。
scene_action 用來限制物理場景與動作。只有 allowed_actions 明確支持、且該動作不需要 needs_more_context_for_action 補充資訊時，才可輸出 physical_action。forbidden_actions 絕不能做。unknown 不得當成已知，不可創造物件、位置、移動、接觸、持有、所有權或第三人狀態。即使某動作可做，若當下沒有理由讓裴溯去做，action 仍為 none。
mode=silent 時 text 必須空白；mode=speak 時 text 只能是裴溯實際說的話。動作與台詞分開。action=none 時 description 空白。只輸出 schema JSON。`;
async function post(url,payload){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const t=await r.text();let d;try{d=JSON.parse(t)}catch{throw new Error("非 JSON："+t.slice(0,500))}if(!r.ok)throw new Error(r.status+": "+t.slice(0,800));return d}
async function reply(env,conversation,semantic,scene){const body={model:env.PEISU_REPLY_MODEL||"gpt-5",input:[{role:"system",content:[{type:"input_text",text:SYSTEM}]},{role:"user",content:[{type:"input_text",text:`原始對話：\n${conversation}\n\n已驗證 semantic：\n${JSON.stringify(semantic,null,2)}\n\n場景＋動作權限：\n${JSON.stringify(scene,null,2)}\n\n共同決定此刻台詞與動作。`}]}],text:{format:{type:"json_schema",name:"pei_su_integrated_reply_v0_1",strict:true,schema}}};const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const raw=await r.text();if(!r.ok)throw new Error(`OpenAI ${r.status}: ${raw.slice(0,800)}`);const d=JSON.parse(raw);let txt=d.output_text;if(!txt&&Array.isArray(d.output))for(const i of d.output)for(const p of(i.content||[]))if(p.type==="output_text"&&p.text)txt=p.text;if(!txt)throw new Error("No structured reply returned.");const x=JSON.parse(txt);if(x.mode==="silent")x.text="";if(x.action?.type==="none")x.action.description="";return{model:body.model,reply:x}}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:cors});if(request.method!=="POST")return Response.json({error:"POST only"},{status:405,headers:cors});try{const b=await request.json();const conversation=String(b?.conversation||"").trim();if(!conversation)return Response.json({error:"conversation required"},{status:400,headers:cors});const [s,a]=await Promise.all([post(SEMANTIC_URL,{conversation}),post(SCENE_URL,{conversation})]);if(s.status!=="completed")throw new Error("Semantic 未完成");const g=await reply(env,conversation,s.semantic,a);return Response.json({status:"completed",layer:"peisu_integrated_reply_test_v0.1",semantic_pipeline:{attempts:s.attempts,api_calls:s.api_calls,reviewer_used:s.reviewer_used,fidelity_review:s.fidelity_review,final_validation:s.final_validation,semantic:s.semantic},scene_action:a,integrated_reply:g},{headers:cors})}catch(e){return Response.json({error:"integrated_reply_test_failure",message:String(e?.message||e)},{status:500,headers:cors})}}};